
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'CONJUCTION DISJUCTION IMPLICATION LPAREN RPAREN VARIABLEstatement : expressionexpression : expression CONJUCTION expressionexpression : expression DISJUCTION expressionexpression : expression IMPLICATION expressionexpression : LPAREN expression RPARENexpression : VARIABLE'
    
_lr_action_items = {'LPAREN':([0,3,5,6,7,],[3,3,3,3,3,]),'VARIABLE':([0,3,5,6,7,],[4,4,4,4,4,]),'$end':([1,2,4,9,10,11,12,],[0,-1,-6,-2,-3,-4,-5,]),'CONJUCTION':([2,4,8,9,10,11,12,],[5,-6,5,5,5,5,-5,]),'DISJUCTION':([2,4,8,9,10,11,12,],[6,-6,6,6,6,6,-5,]),'IMPLICATION':([2,4,8,9,10,11,12,],[7,-6,7,7,7,7,-5,]),'RPAREN':([4,8,9,10,11,12,],[-6,12,-2,-3,-4,-5,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'statement':([0,],[1,]),'expression':([0,3,5,6,7,],[2,8,9,10,11,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> statement","S'",1,None,None,None),
  ('statement -> expression','statement',1,'p_statement_expr','main.py',58),
  ('expression -> expression CONJUCTION expression','expression',3,'p_expression_conjuction','main.py',71),
  ('expression -> expression DISJUCTION expression','expression',3,'p_expression_disjuction','main.py',80),
  ('expression -> expression IMPLICATION expression','expression',3,'p_expression_implication','main.py',87),
  ('expression -> LPAREN expression RPAREN','expression',3,'p_expression_group','main.py',98),
  ('expression -> VARIABLE','expression',1,'p_expression_var','main.py',103),
]
